spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3305/taskmanager}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expirationMinutes: 60
  refreshExpirationDays: 7

logging:
  level:
    org.springframework.security: INFO
